# Generated by Django 3.1.1 on 2020-10-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django102', '0008_auto_20201008_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='level_of_difficulty',
            field=models.IntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard')], default=1),
        ),
    ]
